name: CI/CD

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
      - name: clone github repository
        uses: actions/checkout@master

      - name: install python3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: install poetry
        run: pip install poetry

      - name: create venv and install innotter-core-app dependencies
        run: cd InnotterDjango && poetry install

      - name: run tests for innotter-core-app
        run: cd InnotterDjango && poetry run pytest --cov=.

      - name: run linter for innotter-core-app
        run: cd InnotterDjango && poetry run flake8 .


  build-deploy:
    runs-on: [ubuntu-latest]
    
    needs: [test]

    env:
      HEROKU_KEY: ${{ secrets.HEROKU_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}

    steps:
      - name: clone github repository
        uses: actions/checkout@master

      - name: build docker image of innotter-core-app, push it to heroku and release
        run: cd InnotterDjango && HEROKU_API_KEY=$HEROKU_KEY sudo heroku container:push release -a $HEROKU_APP
